home/urls.py
from django.conf.urls import url
from home import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^admin/', views.my_admin, name='admin'),
]

mkcenter/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^', include('products.urls')),
]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url
from products import views

urlpatterns = [
    url(r'^product/(?P<product_id>\w+)/$', views.product, name='product'),
    url(r'^product/addcomment/(?P<id>\w+)/$', views.addcomment, name='addcomment'),
    url(r'^cat/(?P<category_name>\w+)', views.category, name='category'),
    url(r'^cat/', views.all, name='all'),
]

home/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone


# Create your models here.
class ProductType(models.Model):
    class Meta:
        verbose_name_plural = 'тип'
        verbose_name = 'типы'

    image = models.ImageField(upload_to='products_type_images/')
    name = models.CharField(max_length=20, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name


class Product(models.Model):
    class Meta:
        verbose_name_plural = 'запчасть'
        verbose_name = 'запчасти'

    name = models.CharField(max_length=20)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    short_description = models.TextField(blank=True, null=True, default=None, max_length=100)
    description = models.TextField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    type = models.ForeignKey(ProductType, blank=True, null=True, default=None)

    def __str__(self):
        return "(%s, %s)" % (self.id, self.name)


class ProductImage(models.Model):
    class Meta:
        verbose_name_plural = 'фотография_запчасти'
        verbose_name = 'фотографии_запчасти'

    product = models.ForeignKey(Product, blank=True, null=True, default=None)
    image = models.ImageField(upload_to='products_images/')
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(default=timezone.now)


class Companiya(models.Model):
    class Meta:
        verbose_name_plural = 'Компания'
        verbose_name = 'Компания'

    Tel_Nomer = models.CharField(max_length=20, blank=True)
    Whatsapp_Nomer = models.CharField(max_length=20, blank=True)
    Email = models.EmailField(blank=True)

    def __str__(self):
        return "(%s, %s, %s)" % (self.Tel_Nomer, self.Email, self.Whatsapp_Nomer)


class Comment(models.Model):
    class Meta:
        verbose_name_plural = 'Комментария'
        verbose_name = 'Комментарии'

    name = models.CharField(max_length=50)
    product = models.ForeignKey(Product)
    comment = models.TextField(max_length=1000)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "на %s,  %s написал %s" % (self.product.name, self.name, self.comment)

class Place(models.Model):
    class Meta:
        verbose_name_plural = 'Место на карте'
        verbose_name = 'Место на карте'

    url = models.TextField()

    def __str__(self):
        return "%s" % self.url

products/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'comment']

home/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render
from products.models import ProductImage, ProductType, Companiya, Place
from django.contrib import admin


def home(request):
    products_images_list = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True).order_by(
        '-created')[0:50]
    productType = ProductType.objects.all()

    query = request.GET.get("q")
    if query:
        products_images_list = products_images_list.filter(product__name__icontains=query)



    paginator = Paginator(products_images_list, 10)  # Show 25 products per page

    page = request.GET.get('page')
    try:
        products_images = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        products_images = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        products_images = paginator.page(paginator.num_pages)

    companiya = Companiya.objects.all()
    place = Place.objects.all()[0:1]

    products_images_t = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True)
    context = {
        "products_images": products_images,
        "products_images_t": products_images_t,
        "companiyas": companiya,
        "places": place,
        "productType": productType,
    }
    return render(request, 'landing/home.html', context)


def my_admin(request):
    return render(request, admin)

products/views.py
from products.models import Product, Comment, Companiya, ProductImage, Place
from products.forms import CommentForm
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


def product(request, product_id):
    form = CommentForm
    comment = Comment.objects.filter(product=product_id).order_by('-created')
    product = get_object_or_404(Product, id=product_id)
    companiya = Companiya.objects.all()
    place = Place.objects.all()[0:1]

    content = {
        "companiyas": companiya,
        "places": place,
        "product": product,
        "form": form,
        "comment": comment
    }
    return render(request, 'products/product.html', content)


def addcomment(request, id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comm = form.save(commit=False)
            comm.product = Product.objects.get(id=id)
            form.save()
    return HttpResponseRedirect('/product/%s' % id)


def category(request, category_name):
    products_images_list = ProductImage.objects.filter(product__type__name__contains=category_name)
    companiya = Companiya.objects.all()
    place = Place.objects.all()[0:1]

    paginator = Paginator(products_images_list, 10)  # Show 25 products per page

    page = request.GET.get('page')
    try:
        products_images = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        products_images = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        products_images = paginator.page(paginator.num_pages)

    context = {
        "products_images": products_images,
        "companiyas": companiya,
        "places": place,
    }
    return render(request, 'landing/product.html', context)


def all(request):
    p = ProductImage.objects.all()
    companiya = Companiya.objects.all()
    place = Place.objects.all()[0:1]
    query = request.GET.get("q")
    if query:
        fp = p.filter(product__name__icontains=query)
        return render(request, 'landing/product.html',
                      {'products_images': fp, 'companiyas': companiya, 'places': place})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MK-CENTER</title>
    {% load static %}
    <!--Bootstrap-->

    <!--Custom styles-->
    <script src="{% static "jquery3.js" %}"></script>
    <script src="{% static "js1.min.js" %}"></script>
    <script src="{% static "bootstrap4.js" %}"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap4.css' %}">
    <link rel="stylesheet" href="{% static 'googlefont.css' %}">
    <link rel="icon" href="{% static 'img/logo.jpg' %}">
</head>
<body>
<div class="wrapper">
    <div class="wrapper-content">
        <div class="main-nab-top">
            {% include 'navbar.html' %}
        </div>
        {% block content %}
        {% endblock content %}
    </div>
</div>
{% include 'footer.html' %}

<script src="{% static 'scripts.js' %}"></script>


<script
        src="http://code.jquery.com/jquery-3.2.1.js"
        integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
        crossorigin="anonymous">
</script>
<script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
</script>
<script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
</script>
<script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
        integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous">
</script>
<script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
        integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous">
</script>

</body>
</html>

templates/footer.html
<footer class="page-footer center-on-small-only blue-grey lighten-5 pt-0 footer"
        style="margin-top: 10px;width: 80%;margin-left: 10%">

    <div style="background-color: #424242;position: fixed;left: 0; bottom: 0;width: 100%;color: #ffff62;height: 6%; z-index: 5">
        <div style="padding-top: 0">

            <h5 style="color: #ffff; text-align: left;margin-top: 0.5%">
                    <span>
                        <b style="color: #ffb3b3">Cвяжитесь с нами:  </b>
                    </span>
                {% for companiya in companiyas %}
                      {{ companiya.Tel_Nomer }}{% if companiya == companiya %},  {% endif %}
                {% endfor %}
            </h5>

        </div>
    </div>

    <div class="" style="background-color: white;z-index: -1; text-align: center;border: 5px solid gold">
        <div class="mt-3">
            <h2 style="padding: 5%">
                Место<br> где продаются лучшие, и выгодные, и дешевые по цене автозапчасти.<br> Только один в
                городе, и это<b> МЫ</b>
            </h2>
            <h4 style="width: 80%;margin-left: 10%; text-align: left"><span><b
                    style="color: #ffc107">Наш контакт  </b></span>
                <br><b>Электроная Почта:</b>
                {% for companiya in companiyas %}
                      {{ companiya.Email }},
                {% endfor %}
                <br><b>  Телефон номер: </b>
                {% for companiya in companiyas %}
                      {{ companiya.Tel_Nomer }},
                {% endfor %}
                <br><b>   Ватсап номер:    </b>
                {% for companiya in companiyas %}
                      {{ companiya.Whatsapp_Nomer }},
                {% endfor %}
            </h4>
            <h5 style="margin-top: 3%">Мы находимся
                {% if user.is_authenticated %}
                    <span style="float: right"><a href="{% url 'admin' %}">
                <input class="btn" style="float: right;background-color: darkred;color: white;margin-top: -0.7%"
                       type="submit"
                       value="Admin">
            </a>
                    </span>
                {% endif %}
            </h5>

        </div>
        {% for place in places %}
            <iframe src="{{ place.url }}"
                    width="100%" height="500" frameborder="0" style="border:0;margin-bottom: 40px"
                    allowfullscreen></iframe>
        {% endfor %}
    </div>

</footer>

templates/landing/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="w3-content w3-section my-slide-main">
        <img class="mySlides w3-animate-top my-slide" src="{% static 'img/s1.jpg' %}">
        <img class="mySlides w3-animate-top my-slide" src="{% static 'img/s2.jpg' %}">
        <img class="mySlides w3-animate-top my-slide" src="{% static 'img/s3.jpg' %}">
        <img class="mySlides w3-animate-top my-slide" src="{% static 'img/s4.jpg' %}">
    </div>

    <script>
        var myIndex = 0;
        carousel();

        function carousel() {
            var i;
            var x = document.getElementsByClassName("mySlides");
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "none";
            }
            myIndex++;
            if (myIndex > x.length) {
                myIndex = 1
            }
            x[myIndex - 1].style.display = "block";
            setTimeout(carousel, 5000);
        }
    </script>


    <div class="container-fluid">
        <h1 class="text-center1">
            Категория
        </h1>
        <div class="row" style="width: 80%;margin-left: 10%">
            {% for type in productType %}

                <div class="col-lg-3" style="float: left">
                    {% include 'landing/type.html' %}
                </div>
            {% empty %}
                <h4 style="text-align:center;background-color: rgba(255, 255, 255, 0.5);width: 100%">
                    Пока нет категории
                </h4>
            {% endfor %}
        </div>


        <h1 class="text-center1" style="margin-top: 5%">
            Новые автозапчасти
        </h1>
        <div class="col-md-8">
            {% for product_image in products_images %}
                {% include 'landing/product_item.html' %}
            {% empty %}
                <h4 style="text-align:center;background-color: rgba(255, 255, 255, 0.5);width: 100%;margin-left: 25%">
                    Пока нет автозапчасти
                </h4>
            {% endfor %}
        </div>


        <div class="pagination">
            <span class="my_paginator">
                {% if products_images.has_previous %}
                                        <a href="?page=1" class="my-paginator5">1 страница</a>
                    <a href="?page=





                            {{ products_images.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                       class="previous round my_a">&#8249;</a>
                {% endif %}

                <span class="current"><b style="color: white" class="my-paginator5">
                    Страница {{ products_images.number }} из {{ products_images.paginator.num_pages }}</b>
                </span>

                {% if products_images.has_next %}
                    <a href="?page=
                       {{ products_images.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                       class="next round my_a">&#8250;</a>
                {% endif %}
            </span>
        </div>
    </div>
{% endblock %}

templates/landing/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="w3-content w3-section my-slide-main">
        <img class="mySlides w3-animate-top my-slide" src="{% static 'img/s1.jpg' %}">
        <img class="mySlides w3-animate-top my-slide" src="{% static 'img/s2.jpg' %}">
        <img class="mySlides w3-animate-top my-slide" src="{% static 'img/s3.jpg' %}">
        <img class="mySlides w3-animate-top my-slide" src="{% static 'img/s4.jpg' %}">
    </div>

    <script>
        var myIndex = 0;
        carousel();

        function carousel() {
            var i;
            var x = document.getElementsByClassName("mySlides");
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "none";
            }
            myIndex++;
            if (myIndex > x.length) {
                myIndex = 1
            }
            x[myIndex - 1].style.display = "block";
            setTimeout(carousel, 5000);
        }
    </script>






    <h1 class="text-center1">
        Запчасти
    </h1>

    <div class="container-fluid">

        <div class="col-md-8">
            {% for product_image in products_images %}
                {% include 'landing/product_item.html' %}
            {% empty %}
                <h4 style="text-align:center;background-color: rgba(255, 255, 255, 0.5);width: 100%; margin-left: 25%">
                    Пока нет запчасти на этом категории
                </h4>
            {% endfor %}
        </div>


        <div class="pagination">
            <span class="my_paginator">
                {% if products_images.has_previous %}
                                        <a href="?page=1" style="color: black">1 sahifaga</a>
                    <a href="?page=



                            {{ products_images.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                       class="previous round my_a">&#8249;</a>
                {% endif %}

                <span class="current"><b style="color: white" class="my-paginator5">
                    Страница {{ products_images.number }} из {{ products_images.paginator.num_pages }}</b>
                </span>

                {% if products_images.has_next %}
                    <a href="?page=
                       {{ products_images.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                       class="next round my_a">&#8250;</a>
                {% endif %}
            </span>
        </div>
    </div>
{% endblock %}

templates/landing/product_item.html
<style>
    * {
        color: black;
    }
</style>
<a href="{% url 'product' product_image.product.id %}">
    <div class="product-item">
        <div class="in-line">

            <img src="{{ product_image.image.url }}" class="img-responsive1">

            {% if product_image.product.discount %}
                <div class="discount-container">
                    <span> {{ product_image.product.discount }}%</span>
                </div>
            {% endif %}

            <h3 class="product_item_name"><b> {{ product_image.product.name }} </b></h3>
            <div class="product_item_dis">{{ product_image.product.short_description }}</div>
            <div class="product_item_price">{{ product_image.product.price }} com
            </div>
        </div>
    </div>
</a>

templates/landing/type.html
<style>
    * {
        color: black;
    }

</style>
<a>
    <div class="product-type">
        <form action="/cat/{{ type.name }}" type="submit">
            <input type="image" class="img-responsive3" src="{{ type.image.url }}">
            <input style="width: 100%; height: auto; text-align: center; font-size: x-large; margin-top: -2%"
                   value='{{ type.name }}' readonly>
        </form>
    </div>
</a>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg  fixed-top"
     style="background-color: rgba(0, 0, 0, .6)">
    <a href="/">
        <img class="navbar-brand" style="height: 40px; width: auto;padding: 0;border-radius: 50%"
             src="{% static "img/index2.jpg" %}"/>
    </a>
    <div>
        <form action="{% url 'all' %}" class="form-inline">
            <input style="width: auto" name="q" class="form-control" placeholder="Поиск..." type="text" value="{{ request.GET.q }}">
            <input type="submit" class="btn btn-secondary" value="Искать">
        </form>
    </div>
</nav>

templates/products/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>

        /* Style the tab */
        .tab {
            overflow: hidden;
            background-color: #edffe6;
        }

        /* Style the buttons inside the tab */
        .tab button {
            background-color: inherit;
            border: none;
            outline: none;
            cursor: pointer;
            transition: 0.3s;
            font-size: 17px;
        }

        /* Change background color of buttons on hover */
        .tab button:hover {
            background-color: #fff;
        }

        /* Create an active/current tablink class */
        .tab button.active {
            background-color: #fff;
        }

        /* Style the tab content */
        .tabcontent {
            display: none;
            padding: 6px 12px;
            border: 1px solid #edffe6;
            border-top: none;
        }

        textarea {
            width: 400px;
            height: 80px;
        }

        #id_name {
            height: auto;
            width: 400px;
            margin-right: 10%;
            margin-left: 5%;
        }
    </style>
    <div class="container" style="background-color: #edffe6">
        <div class="row">
            <div class="col-lg-6">
                {% for image_item in product.productimage_set.all %}
                    <div class="product-image-item img-magnifier-container" style="margin: 100px">
                        <img id="myimage" src="{{ image_item.image.url }}" class="img-responsive" style="width: 100%;">
                    </div>
                {% endfor %}
            </div>
            <div class="col-lg-6">
                <h2 class="text-center" style="margin: 50px">
                    {{ product.name }}
                </h2>
                <div class="">
                    <h5>
                        Цена:<br><span style="color: darkred">{{ product.price }} сом</span>
                    </h5>
                </div>
                <h3 style="text-align: center">Описание</h3>
                <hr>
                <div class="product-des">
                    {{ product.description }}
                </div>
            </div>
        </div>
        <div class="container">
            <form style="width:50%" action="/product/addcomment/{{ product.id }}/" method="post">
                {% csrf_token %}
                {{ form.errors }}
                {{ form }}
                <input type="submit" value="Комментировать" class="btn btn-dark"
                       style="margin-left:60%">
            </form>
            <h1><b>Комментарии</b></h1>
            {% for comm in comment %}
                <hr>
                <b>{{ comm.name }}</b>
                <small>    {{ comm.created|timesince }} назад</small><br>
                <b>{{ comm.comment }}</b><br>
                <hr>
            {% empty %}
                <p style="text-align:center">
                    <small>Пока без коментариев</small>
                </p>
            {% endfor %}
        </div>
    </div>
{% endblock %}